# Generated by Django 6.0 on 2025-12-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(help_text='Número de Identificación Tributaria', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la empresa', max_length=150)),
                ('direccion', models.CharField(help_text='Dirección física', max_length=255)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'core_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('proveedor', models.CharField(choices=[('resend', 'Resend API'), ('django_smtp', 'Django SMTP'), ('manual', 'Manual')], default='resend', max_length=20)),
                ('documento_hash', models.CharField(help_text='Hash SHA-256 del PDF para verificación de autenticidad', max_length=64)),
                ('contenido_hash', models.CharField(help_text='Hash SHA-256 del contenido del inventario', max_length=64)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('total_unidades', models.PositiveIntegerField(default=0)),
                ('valor_inventario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen generado por IA del estado del inventario')),
                ('alertas_ia', models.JSONField(default=list, help_text='Lista de alertas generadas por análisis inteligente')),
                ('respuesta_api', models.JSONField(blank=True, default=dict, help_text='Respuesta del servicio de email')),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_envios', to='litethinking_domain.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Envío',
                'verbose_name_plural': 'Historial de Envíos',
                'db_table': 'core_historialenvio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=150)),
                ('caracteristicas', models.TextField(blank=True, help_text='Características y descripción del producto')),
                ('precios', models.JSONField(default=dict, help_text='Precios en diferentes monedas: {"COP": 1000, "USD": 0.25}')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria del producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='litethinking_domain.empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'core_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en stock')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('producto', models.ForeignKey(help_text='Producto en inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='litethinking_domain.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'core_inventario',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
