# Generated by Django 6.0 on 2025-12-24 13:41
# NOTA: Los modelos ahora están en litethinking_domain
# Esta migración se deja vacía para mantener el historial de migraciones

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litethinking_domain', '0001_initial'),  # Depende de la migración del dominio
    ]

    operations = [
        # VACÍO - Los modelos ahora están en litethinking_domain
        # Las tablas core_* son usadas por litethinking_domain con Meta.db_table
    ]
