# Generated by Django 6.0 on 2025-12-24 13:41
# NOTA: Los modelos ahora están en litethinking_domain
# Esta migración se deja vacía para mantener el historial de migraciones
# Las tablas ya existen en producción (creadas originalmente por core)

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # SIN DEPENDENCIAS - Las tablas ya existen en la BD de producción
        # litethinking_domain usa Meta.db_table='core_*' para reusar las tablas existentes
    ]

    operations = [
        # VACÍO - Los modelos ahora están en litethinking_domain
        # Las tablas core_* son usadas por litethinking_domain con Meta.db_table
    ]
