# Generated by Django 6.0 on 2025-12-27 03:26
# NOTA: Los modelos ahora están en litethinking_domain
# Esta migración se deja vacía para mantener el historial de migraciones

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # VACÍO - HistorialEnvio ahora está en litethinking_domain
    ]
