# Generated by Django 6.0 on 2025-12-27 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('proveedor', models.CharField(choices=[('resend', 'Resend API'), ('django_smtp', 'Django SMTP'), ('manual', 'Manual')], default='resend', max_length=20)),
                ('documento_hash', models.CharField(help_text='Hash SHA-256 del PDF para verificación de autenticidad', max_length=64)),
                ('contenido_hash', models.CharField(help_text='Hash SHA-256 del contenido del inventario', max_length=64)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('total_unidades', models.PositiveIntegerField(default=0)),
                ('valor_inventario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen generado por IA del estado del inventario')),
                ('alertas_ia', models.JSONField(default=list, help_text='Lista de alertas generadas por análisis inteligente')),
                ('respuesta_api', models.JSONField(blank=True, default=dict, help_text='Respuesta del servicio de email')),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_envios', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Envío',
                'verbose_name_plural': 'Historial de Envíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
